#this is workflows name
name: hello

#run in triggers
on:
  workflow_dispatch: 
  #push:
    #branches: [main]
#these jobs run inside workflow
jobs:

#this is the name of jobs
    greet:
    #thes is a github runers ,each job run on runner
      runs-on: ubuntu-latest
      steps:
        - name: say hello user
          run: echo 'hello dosto'

        - name: say hello friend
          run: echo 'hello friend'
      
        
